repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Use the latest Black version
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0   # Use the latest Flake8 version
    hooks:
      - id: flake8
        args: ['--extend-ignore=F841']
